# Generated by Django 3.0.5 on 2020-04-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
    ]
