# Generated by Django 3.0.5 on 2020-04-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0004_auto_20200414_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
